<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- <link name="map"/>
    <joint name="world_joint" type="fixed">
        <parent link="world"/>
        <child link="map"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint> -->
    <gazebo>
            <xacro:if value="$(eval sim_type == 'gz_sim')">
                 <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
                    <odom_publisher_frequency>50</odom_publisher_frequency>
                    <left_joint>front_left_wheel_joint</left_joint>
                    <left_joint>back_left_wheel_joint</left_joint>
                    <right_joint>front_right_wheel_joint</right_joint>
                    <right_joint>back_right_wheel_joint</right_joint>
                    <wheel_separation>${base_w}</wheel_separation>
                    <wheel_diameter>${2*wheel_radius}</wheel_diameter>
                    <max_wheel_torque>20</max_wheel_torque>
                    <max_linear_acceleration>1.0</max_linear_acceleration>
                    <topic>cmd_vel</topic>
                    <publish_odom>true</publish_odom>
                    <publish_odom_tf>true</publish_odom_tf>
                    <publish_wheel_tf>true</publish_wheel_tf>
                    <odom_topic>/model/robot/odom</odom_topic>
                    <frame_id>odom</frame_id>
                    <child_frame_id>base_link</child_frame_id>
                </plugin>
        
                <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
                    <update_rate>50</update_rate>
                    <topic>/model/robot/joint_states</topic>
                    <joint_name>front_left_wheel_joint</joint_name>
                    <joint_name>front_right_wheel_joint</joint_name>
                    <joint_name>back_left_wheel_joint</joint_name>
                    <joint_name>back_right_wheel_joint</joint_name>
                </plugin> 
            </xacro:if>
            <xacro:if value="$(eval sim_type == 'gazebo')">
                <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">

                    <!-- Plugin update rate in Hz -->
                    <updateRate>50</updateRate>

                    <num_wheel_pairs>2</num_wheel_pairs>
                    <!-- Name of left joint, defaults to `left_joint` -->
                    <left_joint>front_left_wheel_joint</left_joint>
                    <left_joint>back_left_wheel_joint</left_joint>  
                    <!-- Name of right joint, defaults to `right_joint` -->
                    <right_joint>front_right_wheel_joint</right_joint>
                    <right_joint>back_right_wheel_joint</right_joint>   
    <!-- The distance from the center of one wheel to the other, in meters, defaults to 0.34 m -->
                    <wheel_separation>${base_w}</wheel_separation>

                    <!-- Diameter of the wheels, in meters, defaults to 0.15 m -->
                    <wheel_diameter>${2*wheel_radius}</wheel_diameter>

                    <!-- Wheel acceleration, in rad/s^2, defaults to 0.0 rad/s^2 -->>

                    <!-- Limits -->
                    <max_wheel_torque>20</max_wheel_torque>
                    <max_wheel_acceleration>1.0</max_wheel_acceleration>

                    
                    <!-- Output -->
                    <odometry_frame>odom</odometry_frame>
                    <robot_base_frame>base_link</robot_base_frame>

                    <publish_odom>true</publish_odom>
                    <publish_odom_tf>true</publish_odom_tf>
                    <publish_wheel_tf>true</publish_wheel_tf>
                    <odometry_source>1</odometry_source>
                    
                </plugin>
                <!-- <plugin name="ground_truth_publisher" filename="libgazebo_ros_p3d.so">
                    <update_rate>50</update_rate>

                    <odom_topic>odom</odom_topic>
                    <frame_name>map</frame_name>
                    <body_name>base_link</body_name>
                    <update_rate>50</update_rate>
                    <xyz_offsets>0 0 0</xyz_offsets>
                    <rpy_offsets>0 0 0</rpy_offsets>
                </plugin> -->

            </xacro:if>

                

        </gazebo>

</robot>