move_base_flex:
  ros__parameters:
    global_frame: 'map'
    robot_frame: 'base_link'
    odom_topic: 'odom'

    use_sim_time: true
    force_stop_at_goal: true
    force_stop_on_cancel: true

    planners: ['mesh_planner']
    mesh_planner:
      type: 'cvp_mesh_planner/CVPMeshPlanner'
      cost_limit: 0.8
      publish_vector_field: true
    planner_patience: 10.0
    planner_max_retries: 2
    project_path_onto_mesh: false

    controllers: ['mesh_controller']
    mesh_controller:
      type: 'mesh_controller/MeshController'
      ang_vel_factor: 7.0
      lin_vel_factor: 1.0

    controller_patience: 2.0
    controller_max_retries: 4
    dist_tolerance: 0.2
    angle_tolerance: 0.8
    cmd_vel_ignored_tolerance: 10.0

    mesh_map:
      # input
      # mesh_file: '/home/amock/mesh_nav_ws/src/mesh_navigation_tutorials/mesh_navigation_tutorials/maps/parking_garage.ply'
      mesh_part: '/'
      # storage
      # mesh_working_file: 'parking_garage.h5'
      mesh_working_part: 'mesh'

      # half-edge-mesh implementation
      hem: pmp # pmp (default), lvr

      layers: ['height_diff', 'roughness','inflation']

      height_diff:
        type: 'mesh_layers/HeightDiffLayer'
        factor: 1.0
        threshold: 0.1

      border:
        type: 'mesh_layers/BorderLayer'
        factor: 1.0
        border_cost: 1.0
        threshold: 0.9

      roughness:
        type: 'mesh_layers/RoughnessLayer'
        factor: 1.0
        threshold: 0.6

      inflation:
        type: 'mesh_layers/InflationLayer'
        factor: 1.0
        inflation_radius: 0.25
        inscribed_radius: 0.15
        lethal_value: 1.0
        inscribed_value: 0.4
        repulsive_field: false
      
      steepness:
        type: 'mesh_layers/SteepnessLayer'
        factor: 1.0
        threshold: 0.8
