- topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "/copernicus/odom"
  gz_topic_name: "model/robot/odometry"
  ros_type_name: "geometry_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/copernicus/velodyne/cloud"
  gz_topic_name: "/velodyne/velodyne_points/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "/joint_states"
  gz_topic_name: "/model/copernicus/joint_states"
  gz_type_name: "ignition.msgs.Model"
  ros_type_name: "sensor_msgs/msg/JointState"
  direction: GZ_TO_ROS

- ros_topic_name: "/tf_odom"
  gz_topic_name: "model/copernicus/tf_odom"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/TwistStamped"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "copernicus/imu"
  gz_topic_name: "/model/copernicus/imu/data"
  gz_type_name: "ignition.msgs.IMU"
  ros_type_name: "sensor_msgs/msg/Imu"
  direction: GZ_TO_ROS

- ros_topic_name: "copernicus/odom"
  gz_topic_name: "/model/copernicus/odom"
  gz_type_name: "ignition.msgs.Odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  direction: GZ_TO_ROS